name: Node Continuous Integration

on: 
  pull_request:
    branches: [ main ]

jobs: 
  test_pull_request: 
    runs-on: ubuntu-ltest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-nod@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm start
      # - run: npm run build

